# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'example'

require 'grpc'
require 'hello_pb'

module Example
  module ExampleService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'example.ExampleService'

      rpc :GetExample, ::Example::ExampleRequest, ::Example::ExampleResponse
    end

    Stub = Service.rpc_stub_class
  end
end
